version: "3"

services:
  dev:
    build: .
    image: matiu/tailwind-yew-builder
    volumes:
      - ${INPUT:-./input}:/work/input
      - ${OUTPUT:-./output}:/work/output
      - ${SOURCE_CODE:-../}:/work/source_code
    command: npx tailwindcss -i /work/input/tailwind.css -c /work/input/tailwind.config.js -o /work/output/tailwind.css --minify

  watch:
    build: .
    image: matiu/tailwind-yew-builder
    volumes:
      - ${INPUT:-./input}:/work/input
      - ${OUTPUT:-./output}:/work/output
      - ${SOURCE_CODE:-../}:/work/source_code
    tty: true            # docker run -t
    stdin_open: true     # docker run -i
    command: npx tailwindcss -i /work/input/tailwind.css -c /work/input/tailwind.config.js -o /work/output/tailwind.css --watch

  prod:
    build: .
    image: matiu/tailwind-yew-builder
    volumes:
      - ${INPUT:-./input}:/work/input
      - ${OUTPUT:-./output}:/work/output
      - ${SOURCE_CODE:-../}:/work/source_code
    environment:
      - NODE_ENV=production
    command: /bin/sh prod.sh

volumes:
  input:
  output:
  source_code:
